---
- name: Install default Apache Web Server
  hosts: all

  tasks:
  - name: Install Apache WebServer
    yum: name=httpd state=latest

  - name: Start Apache and Enable ot on every boot
    service: name=httpd state=started enable=yes
